[+++ b/common/src/main/java/io/netty/util/internal/ThreadLocalRandom.java, +import java.lang.Thread.UncaughtExceptionHandler;, +            generatorThread.setDaemon(true);, +            generatorThread.setUncaughtExceptionHandler(new UncaughtExceptionHandler() {, +                @Override, +                public void uncaughtException(Thread t, Throwable e) {, +                    logger.debug("An exception has been raised by {}", t.getName(), e);, +                }, +            });, +            boolean interrupted = false;, +                    generatorThread.interrupt();, +                                    "Not enough entrophy?", timeoutSeconds, +                    );, +                    interrupted = true;, +                    generatorThread.interrupt();, +                    logger.warn("Failed to generate a seed from SecureRandom due to an InterruptedException.");, +                    break;, +, +            if (interrupted) {, +                // restore interrupt status because we don't know how to/don't need to handle it here, +                Thread.currentThread().interrupt();, +            }]