[+++ b/rxjava-core/src/main/java/rx/observers/SafeSubscriber.java, +        } catch (Throwable pluginException) {, +            handlePluginException(pluginException);, +        }, +        try {, +                    try {, +                    } catch (Throwable pluginException) {, +                        handlePluginException(pluginException);, +                    }, +                try {, +                } catch (Throwable pluginException) {, +                    handlePluginException(pluginException);, +                }, +                    try {, +                    } catch (Throwable pluginException) {, +                        handlePluginException(pluginException);, +                    }, +            try {, +            } catch (Throwable pluginException) {, +                handlePluginException(pluginException);, +            }, +    private void handlePluginException(Throwable pluginException) {, +        /*, +         * We don't want errors from the plugin to affect normal flow., +         * Since the plugin should never throw this is a safety net, +         * and will complain loudly to System.err so it gets fixed., +         */, +        System.err.println("RxJavaErrorHandler threw an Exception. It shouldn't. => " + pluginException.getMessage());, +        pluginException.printStackTrace();, +    }, +]