[+++ b/android/guava-tests/test/com/google/common/base/ThrowablesTest.java, +      assertThat(expected).hasCauseThat().isSameAs(cause);, +      assertThat(expected).hasCauseThat().isSameAs(cause);, +++ b/android/guava-tests/test/com/google/common/base/ThrowablesTest.java, +      assertThat(expected).hasCauseThat().isSameAs(cause);, +      assertThat(expected).hasCauseThat().isSameAs(cause);, +++ b/android/guava/src/com/google/common/base/Throwables.java, +        throw new IllegalArgumentException("Loop in causal chain detected.", throwable);, +        throw new IllegalArgumentException("Loop in causal chain detected.", throwable);, +++ b/android/guava-tests/test/com/google/common/base/ThrowablesTest.java, +      assertThat(expected).hasCauseThat().isSameAs(cause);, +      assertThat(expected).hasCauseThat().isSameAs(cause);, +++ b/android/guava/src/com/google/common/base/Throwables.java, +        throw new IllegalArgumentException("Loop in causal chain detected.", throwable);, +        throw new IllegalArgumentException("Loop in causal chain detected.", throwable);, +++ b/guava-tests/test/com/google/common/base/ThrowablesTest.java, +      assertThat(expected).hasCauseThat().isSameAs(cause);, +      assertThat(expected).hasCauseThat().isSameAs(cause);, +++ b/android/guava-tests/test/com/google/common/base/ThrowablesTest.java, +      assertThat(expected).hasCauseThat().isSameAs(cause);, +      assertThat(expected).hasCauseThat().isSameAs(cause);, +++ b/android/guava/src/com/google/common/base/Throwables.java, +        throw new IllegalArgumentException("Loop in causal chain detected.", throwable);, +        throw new IllegalArgumentException("Loop in causal chain detected.", throwable);, +++ b/guava-tests/test/com/google/common/base/ThrowablesTest.java, +      assertThat(expected).hasCauseThat().isSameAs(cause);, +      assertThat(expected).hasCauseThat().isSameAs(cause);, +++ b/guava/src/com/google/common/base/Throwables.java, +        throw new IllegalArgumentException("Loop in causal chain detected.", throwable);, +        throw new IllegalArgumentException("Loop in causal chain detected.", throwable);]